Inn subida dev
SubSeEco/DAES pull request #10
Opened 2023-11-13 16:47 UTC by RamonInnova

-correcciones en documentos
-reordenamientos de campos en reforma ant/post/gremial
-se elimino la observaciones para reforma ant

2023-11-14 12:44 UTC, IgnacioRocha requested changes
@RamonInnova @AlexGonzalezM @mrspolainas @AngelikMaldona2 
Revisando el codigo, no solo los archivos modificados y los archivos en la carpeta compartida por Carlos Morales, encontramos que aun se esta usando la libreria iText 5.5.13.2 en las capas DAES.BLL, DAES.Infrastructure y los metodos del archivo `HSM.cs`
ya que estos no coinciden con lo enviado en el commit [#cfa811a](https://github.com/SubSeEco/DAES/commit/cfa811a10201d35ace5970321fc486c12b273935)
![image](https://github.com/SubSeEco/DAES/assets/126517611/e5b202b3-8087-4de2-9972-ede5bc7ee8c2)
![image](https://github.com/SubSeEco/DAES/assets/126517611/f00fec87-a871-4144-91f8-5e8b03397f97)
![image](https://github.com/SubSeEco/DAES/assets/126517611/da292116-9180-444c-bced-ac8e3a58a642)

2023-11-14 12:58 UTC, mrspolainas commented
Gracias @IgnacioRocha , lo estaremos revisando.

2023-11-14 15:14 UTC, mrspolainas commented
@IgnacioRocha ¿Cuál debiera ser la versión que debemos manejar?

2023-11-14 15:36 UTC, IgnacioRocha commented
@mrspolainas la libreria es iText-LGPL 4.1.6, los cambios se encuentran en el commit [#cfa811a](https://github.com/SubSeEco/DAES/commit/cfa811a10201d35ace5970321fc486c12b273935) para que sean revisados.

2023-11-14 16:43 UTC, RamonInnova commented
ya están arriba los cambios de iTextSharp-LGPL version 4.1.6

2023-11-14 17:35 UTC, IgnacioRocha commented
@RamonInnova @AlexGonzalezM @mrspolainas 
Se revisaron los cambios y efectivamente se actualizo la libreria en las capas, DAES.BLL y DAES.Infrastructure.
Solo que los archivos HSM.cs y File.cs no tienen correctamente implementados los metodos.
![image](https://github.com/SubSeEco/DAES/assets/126517611/5f230366-f444-4cc7-b0d1-9ba1739dc2a0)
![image](https://github.com/SubSeEco/DAES/assets/126517611/6ffacd6b-7d97-43fe-a50b-0df83648874d)

2023-11-14 18:28 UTC, RamonInnova commented
se ha adaptado los archivos señalados

2023-11-15 11:30 UTC, IgnacioRocha approved these changes
@RamonInnova @mrspolainas @AlexGonzalezM 
De acuerdo a lo conversado en reunión y como se indico en la misma, el modulo de Existencia Posterior aun esta en revisión por parte de ustedes, se aceptan los cambios y las correcciones indicadas.

2023-11-15 11:37 UTC, IgnacioRocha commented
Se resolvieron los conflictos de codigo en alos archivos web.config, Custom.cs.
Se aprueba el PR a la espera de la corrección del modulo Existencia Posterior.

2023-11-15 11:37 UTC, closed without merging