Inn subida dev
SubSeEco/DAES pull request #6
Opened 2023-10-13 21:01 UTC by RamonInnova

Requerimiento 1 parte 2, sin template de estatutos

-ahora existen observaciones/oficios hacia existencia legal y reformas
-retoque de formulario para 8votransitorio
-optimización en la creación automática de certificados

2023-10-16 19:17 UTC, IgnacioRocha requested changes
Favor corregir libreria EPPlus en Infrastructure, Model y FrontOffice y explicar motivo de cambio en Web.config de Front Office

2023-10-16 19:38 UTC, IgnacioRocha requested changes
Corregir segun lo indicado.

2023-10-16 19:38 UTC, IgnacioRocha commented on DAES.Infrastructure/DAES.Infrastructure.csproj
> +    </Reference>
Esta referencia a la libreria no es requerida en Infrastructure.
```suggestion
```

2023-10-16 19:38 UTC, IgnacioRocha commented on DAES.Web.FrontOffice/Web.config
> +  </configBuilders>
Explicar en este hilo el motivo del por que se agrego esta configuracion al web.config.

2023-10-16 19:38 UTC, IgnacioRocha commented on DAES.Web.FrontOffice/DAES.Web.FrontOffice.csproj
> +    </Reference>
Referencia no necesaria ya que el ciudadano no genera ni solicita documentacion en Excel.
```suggestion
```

2023-10-16 19:38 UTC, IgnacioRocha commented on DAES.Infrastructure/packages.config
> +  <package id="EPPlus" version="4.5.2.1" targetFramework="net48" />
```suggestion
```

2023-10-16 19:38 UTC, IgnacioRocha commented on DAES.Model/packages.config
> +  <package id="EPPlus" version="4.5.2.1" targetFramework="net48" />
Referencia no necesaria en la capa de Modelo.
```suggestion
```

2023-10-19 13:06 UTC, RamonInnova commented on DAES.Web.FrontOffice/DAES.Web.FrontOffice.csproj
> +    </Reference>
si entendi bien, debo sacar EPPlus.4.5.2.1 de model, infrastructure y front, la los desintale y subi la nueva version con los documentos de estatutos

2023-10-19 17:51 UTC, RamonInnova commented
elimine en el Web.config de Front Office el componente configBuilders

2023-10-19 18:20 UTC, IgnacioRocha commented on DAES.BLL/Custom.cs
Revisando el funcionamiento de la emision de certificados, al solicitar uno de Vigencia y Estatutos, aun presenta errores al no encontrar el TipoDocumentoId 103.
![image_2023-10-19_151941550](https://github.com/SubSeEco/DAES/assets/126517611/102c39ba-5a6c-4043-a3a8-c0c22c1083c8)

![image_2023-10-19_151921587](https://github.com/SubSeEco/DAES/assets/126517611/018fd3e8-e28e-4e91-b2b6-91b4682553af)

2023-10-20 15:00 UTC, IgnacioRocha approved these changes
Se probaron los modulos de BO y FO, funcionando todos sin ningun inconveniente.

2023-10-20 15:01 UTC, merged